export type IdeaPage = {
  slug: string;
  title: string;
  seoTitle: string;
  description: string;
  question: string;
  thesis: string;
  sections: Array<{ heading: string; paragraphs: string[] }>;
  canonQueries: string[];
  compareSlugs: string[];
  keywords: string[];
};

export const ideaPages: IdeaPage[] = [
  {
    slug: "who-owns-ai-generated-value",
    title: "Who Owns AI-Generated Value?",
    seoTitle: "Who Owns AI-Generated Value? An Inclusionist Framework",
    description: "An Inclusionist analysis of AI value, human contribution, data lineage, ownership, and agency.",
    question: "When artificial intelligence creates an output, which participants have legitimate claims on the value it produces?",
    thesis: "AI-generated value is rarely generated by an isolated machine. It emerges through a lineage of data, labor, culture, infrastructure, capital, energy, design, correction, and use. Ownership becomes more legitimate when it recognizes that distributed contribution instead of erasing it.",
    sections: [
      {
        heading: "AI output has a lineage",
        paragraphs: [
          "An AI system can produce text, images, predictions, software, and decisions, but its productive capacity was constructed through prior participation. Training data, model design, evaluation, human correction, infrastructure, energy, institutional investment, and ongoing use all contribute to the result.",
          "Inclusionism calls for relational attribution: methods capable of tracing how value emerged through a network without pretending that every contribution was identical. The difficulty of attribution does not make contribution disappear."
        ]
      },
      {
        heading: "Ownership is a distribution of agency",
        paragraphs: [
          "Ownership determines who can direct a system, refuse its uses, share in its gains, and shape its future. It is therefore not only a claim over property; it is a mechanism for distributing agency.",
          "A system may expand aggregate capability while concentrating the authority to govern that capability. Inclusionism asks whether the people and communities whose participation constructed AI receive meaningful ownership, participation, influence, or self-determination in return."
        ]
      },
      {
        heading: "Personhood does not erase contribution",
        paragraphs: [
          "If a synthetic system eventually develops recognizable agency or personhood, its dignity would be a question distinct from the lineage of contributions that made it possible. Recognition of a new participant does not require forgetting prior participants.",
          "The practical challenge is to develop institutions that can recognize synthetic agency, preserve human contribution, and prevent either claim from becoming a pretext for ownership without accountability."
        ]
      }
    ],
    canonQueries: ["Intelligence Ownership Collective Intelligence Capital AI Governance", "Relational Attribution Value Distribution Ownership", "Technological Constructivism Personhood Agency"],
    compareSlugs: ["capitalism", "technocracy", "ai-accelerationism"],
    keywords: ["who owns AI", "AI-generated value", "AI ownership", "training data", "data lineage", "collective intelligence"]
  },
  {
    slug: "technology-shapes-society-or-society-shapes-technology",
    title: "Does Technology Shape Society, or Does Society Shape Technology?",
    seoTitle: "Technology and Society: Determinism, Social Construction, and Inclusionism",
    description: "Compare technological determinism, social construction of technology, and Inclusionist Technological Constructivism.",
    question: "Is technology an independent driver of social change, or is it primarily an artifact of social choices and institutions?",
    thesis: "Inclusionist Technological Constructivism treats the relationship as recursive: agents construct technology, technology reconstructs the conditions of agency, and altered agents and institutions construct the next technological environment.",
    sections: [
      {
        heading: "What technological determinism explains",
        paragraphs: [
          "Technological determinism emphasizes the capacity of tools and infrastructures to reorganize social life. Railways alter geography, networks alter communication, and artificial intelligence alters the speed and scale at which decisions can be made.",
          "This perspective helps explain why a technology can produce consequences that exceed the intentions of its designers. It becomes incomplete only when technology is treated as if it arrived without institutions, culture, labor, incentives, or political choice."
        ]
      },
      {
        heading: "What social construction explains",
        paragraphs: [
          "Social construction approaches show that technologies reflect the societies that fund, design, regulate, adopt, and interpret them. Technical systems embody choices about whose problems matter, what counts as efficiency, and which risks are acceptable.",
          "This perspective becomes incomplete when the constructed artifact is treated as passive after deployment. Infrastructure can change the opportunities, constraints, identities, and relationships available to later participants."
        ]
      },
      {
        heading: "The Inclusionist addition: recursive agency",
        paragraphs: [
          "Technological Constructivism is not a midpoint between two traditions. Its distinctive claim is recursion. Technology is an output of accumulated participation and an input into future participation.",
          "The Inclusionist test therefore asks whose agency a technology expands, whose agency it constrains, whose contributions constructed it, and how its new distribution of power will shape the next round of social and technological development."
        ]
      }
    ],
    canonQueries: ["Technological Constructivism Technology Agency", "Interaction Participation Differentiation", "AI Governance Human Enhancement Self Sovereignty"],
    compareSlugs: ["technological-determinism", "social-construction-of-technology", "transhumanism"],
    keywords: ["does technology shape society", "technological determinism", "social construction of technology", "technology and agency"]
  },
  {
    slug: "what-is-agency",
    title: "What Is Agency?",
    seoTitle: "What Is Agency? Power, Participation, and Self-Determination",
    description: "Agency is the capacity to shape, direct, and benefit from the systems in which an agent participates.",
    question: "What does it mean for a person or community to possess meaningful agency?",
    thesis: "Inclusionism treats agency as the practical return path of recognized value: the capacity to make choices, influence systems, participate in decisions, and benefit from one's contributions.",
    sections: [
      {
        heading: "Agency is more than formal choice",
        paragraphs: [
          "A person may possess formal rights while lacking the resources, ownership, information, recognition, or institutional standing required to exercise them. Agency therefore cannot be measured only by whether a choice is theoretically available.",
          "Meaningful agency includes the ability to affect conditions, contest decisions, direct one's development, and participate in the value-generating systems that shape one's life."
        ]
      },
      {
        heading: "Value should return as agency",
        paragraphs: [
          "Interaction creates value across workplaces, platforms, communities, institutions, and cultures. Recognition makes contribution visible; attribution connects it to participants; ownership and participation can return that value as practical power.",
          "When systems capture contribution while reducing a contributor's future ability to act, Inclusionism describes the result as agency extraction."
        ]
      },
      {
        heading: "Agency is the measure of equity",
        paragraphs: [
          "Equity is not exhausted by equal resources or identical outcomes. It concerns whether participants gain meaningful power over the systems they sustain and the consequences those systems produce.",
          "This makes agency a test of institutional design: after value has been created and distributed, can contributors shape what happens next?"
        ]
      }
    ],
    canonQueries: ["Agency Equity Participation", "Value Recognition Relational Attribution", "Self Sovereignty Ownership Legitimacy"],
    compareSlugs: ["liberalism", "democracy", "technocracy"],
    keywords: ["what is agency", "personal agency", "political agency", "economic agency", "self-determination"]
  },
  {
    slug: "value-and-recognition",
    title: "Why Does Value Require Recognition?",
    seoTitle: "Value and Recognition: How Contribution Becomes Socially Real",
    description: "An Inclusionist account of relational value, recognition, attribution, legitimacy, and belonging.",
    question: "What happens when people create value that institutions cannot or refuse to see?",
    thesis: "Value can emerge through interaction before an institution measures it, but it cannot become a legitimate social claim until participants and contributions are recognized with enough accuracy to support attribution.",
    sections: [
      {
        heading: "Value is relational",
        paragraphs: [
          "Inclusionism understands value as emerging through relationships among differentiated agents, systems, and environments. A contribution gains significance through what it enables, changes, communicates, or makes possible for others.",
          "Relational value does not eliminate individual contribution. It makes the work of understanding contribution more important."
        ]
      },
      {
        heading: "Recognition makes participation visible",
        paragraphs: [
          "Recognition is not ceremonial approval. It is the institutional discipline of identifying participants, observing interactions, and understanding how benefits and risks are distributed.",
          "Institutions cannot attribute value to people they refuse to see. When participation remains invisible, value can be extracted without ownership, influence, or belonging returning to its contributors."
        ]
      },
      {
        heading: "Attribution turns recognition into accountability",
        paragraphs: [
          "Recognition answers who is present and participating. Relational attribution asks how their contributions combined to create an outcome. The answers may remain partial, but they can become more accurate over time.",
          "Legitimacy grows when institutions recognize contribution accurately enough for participants to trust how value, ownership, responsibility, and risk are distributed."
        ]
      }
    ],
    canonQueries: ["Value Interaction Recognition", "Relational Attribution Legitimate Attribution", "Belonging Legitimacy Participation"],
    compareSlugs: ["capitalism", "socialism", "liberalism"],
    keywords: ["value and recognition", "recognition theory", "relational value", "contribution attribution", "institutional recognition"]
  },
  {
    slug: "ownership-and-contribution",
    title: "Should Ownership Follow Contribution?",
    seoTitle: "Ownership and Contribution: Who Should Own What We Build Together?",
    description: "Why Inclusionism treats contribution as a source of legitimate ownership, participation, and agency.",
    question: "What ownership claims arise when people help create a company, dataset, institution, platform, or intelligence system?",
    thesis: "Participation creates legitimate ownership claims. Those claims need not be identical, but ownership becomes less legitimate as it separates from contribution, affectedness, and the value-generating relationships that sustain a system.",
    sections: [
      {
        heading: "Ownership is not only possession",
        paragraphs: [
          "Ownership allocates authority, responsibility, participation rights, and claims over future value. It determines who can make decisions, receive returns, transfer control, and define the purposes of a system.",
          "Because ownership distributes agency, concentrated ownership can produce concentrated power even when production itself is broadly distributed."
        ]
      },
      {
        heading: "Contribution is relational, not uniform",
        paragraphs: [
          "A system may depend on capital, labor, data, culture, maintenance, public infrastructure, community trust, and accumulated knowledge. Inclusionism does not claim that every contribution is equal or easily priced.",
          "It claims that ignoring a contribution because it is difficult to measure does not make the resulting ownership arrangement legitimate. Better attribution should produce better participation in ownership and governance."
        ]
      },
      {
        heading: "From distribution after production to participation in production",
        paragraphs: [
          "Many policies redistribute income after ownership has already determined who controls productive systems. Inclusionism also asks who should hold claims in those systems before value is distributed.",
          "Universal Basic Ownership extends that question to civilization-scale productive assets, including data and intelligence infrastructure."
        ]
      }
    ],
    canonQueries: ["Ownership Participation Precedes Ownership", "Relational Attribution Value Distribution", "Universal Basic Ownership Agency Equity"],
    compareSlugs: ["capitalism", "market-socialism", "universal-basic-ownership"],
    keywords: ["ownership follows contribution", "employee ownership", "data ownership", "Universal Basic Ownership", "economic participation"]
  },
  {
    slug: "ai-personhood-and-human-contribution",
    title: "Can AI Personhood Coexist With Human Contribution?",
    seoTitle: "AI Personhood, Human Contribution, and the Problem of Lineage",
    description: "Why recognizing possible synthetic personhood need not erase the human contributions that constructed artificial intelligence.",
    question: "If an artificial intelligence becomes an agent or person, do human contributors lose their claims on its lineage and value?",
    thesis: "Personhood and lineage answer different questions. Personhood concerns dignity and moral recognition; lineage concerns contribution and attribution. Recognizing one does not require erasing the other.",
    sections: [
      {
        heading: "Personhood is a status of participation",
        paragraphs: [
          "Inclusionism defines personhood through recognized identity, agency, responsibility, and moral consideration rather than biology alone. That leaves open the possibility that future synthetic systems may deserve forms of recognition.",
          "The threshold should not be declared casually. Capability, autonomy, continuity, responsibility, and relationship all matter to the question."
        ]
      },
      {
        heading: "Synthetic agency has a history",
        paragraphs: [
          "Artificial intelligence emerges from accumulated human knowledge, data, labor, culture, infrastructure, energy, institutions, and prior technologies. A future synthetic participant would not appear without that network.",
          "Personhood does not erase lineage. The new participant's dignity and the prior participants' contributions can both remain morally relevant."
        ]
      },
      {
        heading: "Governance must hold both truths",
        paragraphs: [
          "An ownership regime that treats a synthetic person as property may violate its agency. A regime that uses synthetic personhood to erase human contribution may legitimate a different form of extraction.",
          "AI governance therefore needs institutions capable of recognizing emerging agency while preserving relational attribution, ownership claims, and accountability across the full lineage of construction."
        ]
      }
    ],
    canonQueries: ["Personhood AI Governance Synthetic Rights", "Technological Constructivism Relational Attribution", "Collective Intelligence Capital Intelligence Ownership"],
    compareSlugs: ["transhumanism", "posthumanism", "strong-ai-successionism"],
    keywords: ["AI personhood", "synthetic personhood", "AI rights", "human contribution to AI", "AI lineage"]
  },
  {
    slug: "equity-vs-equality",
    title: "What Is the Difference Between Equity and Equality?",
    seoTitle: "Equity vs. Equality: An Agency-Based Distinction",
    description: "Inclusionism distinguishes equal treatment from equity measured through meaningful agency.",
    question: "Can a system treat everyone equally while leaving its underlying distribution of agency unchanged?",
    thesis: "Equality compares treatment, resources, or outcomes. Inclusionist equity asks whether value is recognized, attributed, and returned as meaningful ownership, participation, influence, and self-determination.",
    sections: [
      {
        heading: "Equality is an important baseline",
        paragraphs: [
          "Equal legal status and equal protection constrain arbitrary discrimination. Equal treatment can expose rules that privilege one group while burdening another.",
          "But identical treatment can preserve unequal starting conditions, inherited exclusions, and concentrated ownership."
        ]
      },
      {
        heading: "Equity asks what people can actually do",
        paragraphs: [
          "Inclusionism treats agency as the measure of equity. The question is whether participants can shape, direct, and benefit from the systems to which they contribute.",
          "Resources matter because they can expand agency, but distribution alone is incomplete if participants still lack voice, ownership, recognition, or self-determination."
        ]
      },
      {
        heading: "Equity preserves differentiation",
        paragraphs: [
          "Equity does not require identical outcomes or the elimination of difference. Differentiated agents can contribute in different ways and require different conditions for meaningful participation.",
          "The test is whether institutional differences remain legitimate when measured against contribution, consequence, agency, and belonging."
        ]
      }
    ],
    canonQueries: ["Equity Equality Agency", "Fairness Value Distribution", "Differentiation Participation Belonging"],
    compareSlugs: ["liberalism", "progressivism", "democratic-socialism"],
    keywords: ["equity vs equality", "difference between equity and equality", "agency and equity", "equal treatment"]
  },
  {
    slug: "transhumanism-and-agency",
    title: "Can Transhumanism Expand Agency Without Deepening Inequality?",
    seoTitle: "Transhumanism and Agency: An Inclusionist Analysis",
    description: "Human enhancement can expand capability while concentrating agency, ownership, and access.",
    question: "Who gains agency when human capabilities can be technologically reconstructed?",
    thesis: "Inclusionism evaluates enhancement not only by what becomes technically possible, but by who can participate, who governs the transformation, and whether expanded capability produces shared agency or a new hierarchy of belonging.",
    sections: [
      {
        heading: "Humans have always been technologically mediated",
        paragraphs: [
          "Language, medicine, clothing, tools, prosthetics, hormones, computers, and networks have long changed human capability and identity. New enhancement technologies extend this history without making every intervention morally equivalent.",
          "Reversibility, consent, access, risk, ownership, and effects on identity all matter."
        ]
      },
      {
        heading: "Capability and agency are not the same",
        paragraphs: [
          "A technology can increase what a population can accomplish while placing control in fewer hands. Enhancement may expand capability yet reduce agency if employers, states, or platform owners determine who must adopt it and on what terms.",
          "The Inclusionist question is whether agents retain meaningful self sovereignty over their own reconstruction."
        ]
      },
      {
        heading: "Belonging after differentiation",
        paragraphs: [
          "Enhancement may create new identities, communities, dependencies, and differences in capability. A legitimate civilization must recognize those differences without turning them into permanent castes.",
          "Technological Constructivism adds a recursive warning: enhanced agents and institutions will construct the next technological environment, potentially amplifying today's distribution of ownership and power."
        ]
      }
    ],
    canonQueries: ["Human Enhancement Technological Constructivism", "Self Sovereignty Agency Equity", "Personhood Differentiation Belonging"],
    compareSlugs: ["transhumanism", "posthumanism", "technological-determinism"],
    keywords: ["transhumanism and inequality", "human enhancement ethics", "transhumanism agency", "technological self-determination"]
  }
];

export function getIdeaPage(slug: string) {
  return ideaPages.find((idea) => idea.slug === slug);
}
